# Render.com deployment configuration for HomeWiz Frontend
# This file defines the frontend web service for deployment

services:
  # Frontend Web Service
  - type: web
    name: homewiz-frontend
    env: node
    plan: starter
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_TELEMETRY_DISABLED
        value: 1
      - key: NEXT_PUBLIC_DEMO_MODE
        value: true
      - key: NEXT_PUBLIC_CLERK_SIGN_IN_URL
        value: /sign-in
      - key: NEXT_PUBLIC_CLERK_SIGN_UP_URL
        value: /sign-up
      - key: NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL
        value: /dashboard
      - key: NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL
        value: /onboarding
      - key: NEXT_PUBLIC_ENABLE_ANALYTICS
        value: true
      - key: NEXT_PUBLIC_ENABLE_ERROR_REPORTING
        value: true
      - key: NEXT_PUBLIC_ENABLE_REAL_TIME_COLLABORATION
        value: true
      - key: NEXT_PUBLIC_ENABLE_AUTO_SAVE
        value: true
      - key: NEXT_PUBLIC_ENABLE_SMART_VALIDATION
        value: true
      - key: NEXT_PUBLIC_ENABLE_COMPRESSION
        value: true
      - key: NEXT_PUBLIC_CACHE_TTL
        value: 3600
      - key: NEXT_PUBLIC_RATE_LIMIT_REQUESTS
        value: 100
      - key: NEXT_PUBLIC_RATE_LIMIT_WINDOW
        value: 900000
      - key: NEXT_PUBLIC_MAX_FILE_SIZE
        value: 10485760
      - key: NEXT_PUBLIC_ALLOWED_FILE_TYPES
        value: pdf,jpg,jpeg,png,doc,docx
      - key: SESSION_TIMEOUT
        value: 86400000
      - key: NEXT_PUBLIC_APP_NAME
        value: HomeWiz
      - key: NEXT_PUBLIC_APP_VERSION
        value: 1.0.0
      - key: NEXT_PUBLIC_LOG_LEVEL
        value: info
    # API Configuration (Disabled - using Supabase cloud)
    - key: NEXT_PUBLIC_DISABLE_BACKEND
      value: true
    # - key: NEXT_PUBLIC_API_URL
    #   value: http://localhost:8000

    # Supabase Configuration (Cloud/Production)
    # Replace these with your actual Supabase project credentials
    - key: NEXT_PUBLIC_SUPABASE_URL
      value: https://your-project-ref.supabase.co
    - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
      value: your_anon_key_here
    # - key: NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
    #   sync: false
    # - key: CLERK_SECRET_KEY
    #   sync: false
    # - key: NEXT_PUBLIC_SENTRY_DSN
    #   sync: false
